### PR TITLE
fix(previews): add checks to create payment preview messages

### LINKED ISSUE #552: fix(sidebar): fix payment preview
Captura de ecrã 2024-09-13, às 15 24 55

flow
- send or request a payment
- appears like that on sidebar

browser - chrome

### PR DESCRIPTION
**Pull request by Jekrimo**
### What this PR does 📖

- Add extra checks for message previews to include payments, add translations for the preview texts

### Which issue(s) this PR fixes 🔨

- Resolve #552 

### Special notes for reviewers 🗒️

Big thing I was looking to do is have the messages apply correctly for who sent, and who is receiving and using the correct grammar depending on who sent/received

image

### CODE REVIEW

File: src/lib/components/messaging/ChatPreview.svelte [hunk 1]
```diff
@@ -30,8 +31,30 @@
 
     let timeago = getTimeAgo(chat.last_message_at)
     const dispatch = createEventDispatcher()
+    let ownId = get(Store.state.user)
+    $: messagePreview =
```
Comment (lgmarchi) [inline src/lib/components/messaging/ChatPreview.svelte]:
```js
$: messagePreview = (() => {
    if (!chat.last_message_id) {
        return $_("message_previews.none");
    }

    if (chat.last_message_id && !chat.last_message_preview) {
        return $_("message_previews.attachment");
    }

    if (chat.last_message_preview.startsWith("/request")) {
        try {
            const sendingUserId = ConversationStore.getMessage(chat.id, chat.last_message_id)?.details.origin;
            const sendingUserDetails = get(Store.getUser(sendingUserId!));
            const { amountPreview } = JSON.parse(chat.last_message_preview.slice(8));
            
            return sendingUserId !== ownId.key
                ? $_("message_previews.coin_requested", { values: { username: sendingUserDetails.name, amount: amountPreview } })
                : $_("message_previews.request_sent", { values: { amount: amountPreview } });
        } catch (error) {
            return "Invalid message format";
        }
    }

    return chat.last_message_preview;
})();
```

@Jekrimo Would be possible to test this suggestion I made? I think is more clear this way.

**Review by lgmarchi — CHANGES_REQUESTED** [review]
I requested a change to let code more clear.

**Review by lgmarchi — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]
