### PR TITLE
fix(mobile): Hide initial sidebar on mobile

### LINKED ISSUE #908: bug(mobile): User should land on homepage
**Issue:**
When the user creates a new account when they land in the app they land with the sidebar already open. Instead they should land on the homepage 

**STR:**
- Create account on mobile device 
- Notice you land with sidebar open

**Screenshots:**

Page you land on 
Screenshot 2024-12-03 at 7 33 19 PM

Page you should land on
Screenshot 2024-12-03 at 7 33 38 PM

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Hides the sidebar during first time login on mobile

### Which issue(s) this PR fixes 🔨

-   Resolve #908

### CODE REVIEW

File: src/lib/state/ui/index.ts [hunk 1]
```diff
@@ -36,7 +37,7 @@ class Store {
             emojiFont: createPersistentState("uplink.ui.emojiFont", EmojiFont.Fluent),
             theme: createPersistentState("uplink.ui.theme", "default"),
             cssOverride: createPersistentState("uplink.ui.cssOverride", ""),
-            sidebarOpen: createPersistentState("uplink.ui.sidebarOpen", true),
+            sidebarOpen: createPersistentState("uplink.ui.sidebarOpen", !checkMobile()),
```
Comment (lgmarchi) [inline src/lib/state/ui/index.ts:40]: @Flemmli97 It will apply for small width in web as well, is correct?

**Review by lgmarchi — CHANGES_REQUESTED** [review]

File: src/lib/state/ui/index.ts (hunk 1 above)
Comment (Flemmli97) [reply src/lib/state/ui/index.ts:40]: yes. and i think thats good. a thing to note is that it only applies the first time someone opens the app.
So if someone is opening the app already in a small window then this behaviour is desired

**Review by lgmarchi — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]
