### PR TITLE
fix(Multipass): Guarantee name not come as undefiend on toast message when receive a friend request

### LINKED ISSUE #242: bug(toast): when adding a user for the first time, undefined is shown on toast instead of username
1. Create two fresh accounts
2. Add UserB as a friend
3. On UserB account, a toast notification is displayed showing "undefined sent a request"

Note: This only happens on first time adding a user. If friend request is accepted, and user is removed/blocked, when adding user again, now the toast notification shows the username correct

image

### PR DESCRIPTION
**Pull request by lgmarchi**
…friend request

### Which issue(s) this PR fixes 🔨

- Resolve #242

### CODE REVIEW

File: src/lib/wasm/MultipassStore.ts [hunk 1]
```diff
@@ -59,7 +59,20 @@ class MultipassStore {
...
                         let incoming = await this.identity_from_did(event.did)
-                        Store.addToastNotification(new ToastMessage("New friend request.", `${incoming?.name} sent a request.`, 2), Sounds.Notification)
+                        let count = 0
+                        while (incoming === undefined) {
+                            incoming = await this.identity_from_did(event.did)
+                            count++
+                            if (count > 15) {
+                                break;
+                            }
+                            await new Promise(resolve => setTimeout(resolve, 1000));
```
Comment (InfamousVague) [inline src/lib/wasm/MultipassStore.ts]: so does this retry for 15 times once per second? Maybe we should move these values into `src/lib/config.ts` as "MAX_RETRY" and "RETRY_TIMEOUT" so that we can easily update the same logic elsewhere. 

Small other note to remove extra `;`. I think this method overall is fine but perhaps we can build a retry util in polling.ts to try again in 500ms then wait 1000ms, 1500ms, 2000ms, etc so that each time it fails we wait a bit longer but early on we can retry very fast. For now though I wouldn't worry about this just something to keep in mind.

**Review by InfamousVague — APPROVED** [review]
