### PR TITLE
fix(raygun): fix raygun event not received

### LINKED ISSUE #295: bug(wasm): Conversation events not received
For some reason conversation events (create/delete conversation) are not received thus e.g. creating a chat only displays it for the current user and not the other user.

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Fixes raygun events not being received. It seems adding a delay will solve that. The cause is unknown

- Resolves #295

### CODE REVIEW

File: src/lib/wasm/RaygunStore.ts [hunk 1]
```diff
@@ -110,6 +110,8 @@ class RaygunStore {
                 this.initConversationHandlers(r)
                 // handleRaygunEvent must be called after initConversationHandlers
                 // this is because if 'raygun.raygun_subscribe' is called before 'raygun.list_conversations', it causes 'raygun.list_conversations' to hang. (reason currently unknown)
+                // update: a delay is (also?) needed as otherwise raygun events are not received
+                await new Promise(f => setTimeout(f, 100))
```
Comment (ashneverdawn) [inline src/lib/wasm/RaygunStore.ts:114]: I get this is a workaround, but if possible I'd avoid adding arbitrary delays like this. we can't guarantee that whatever needs to happen will within 100ms. And setting a large value would cause unnecessary delays.

Generally, it would be better to have the prerequisite action complete and then fire an event or something that point which would trigger the next line to run.

Comment (Flemmli97) [reply src/lib/wasm/RaygunStore.ts]: i just rewrote the logic here to instead retry again after a while if its hanging

**Review by ashneverdawn — APPROVED** [review]

**Review by tooshel — APPROVED** [review]

**Review by dariusc93 — APPROVED** [review]
lgtm for the intern solution, though it might be best to investigate into the actual cause. Imho it might be something with how we handle `handleRaygunEvent` within svelte that is affecting the event loop for that specific promise.
