### PR TITLE
fix(Chat): Fix stickers selector search bar

### LINKED ISSUE #594: bug(chats): sticker search bar does nothing
1. Go to any conversation
2. Open sticker picker
3. Type something in the search bar that could return matching results (collection name or sticker name)
4. You will see that nothing happens
5. Press enter
6. You will see that nothing happens

https://github.com/user-attachments/assets/fc18f29d-1297-45b6-81cb-aed50117778e

### PR DESCRIPTION
**Pull request by lgmarchi**
### What this PR does 📖

- Fix stickers selector search bar

https://github.com/user-attachments/assets/440c1820-5441-49bc-8446-f539c55f6b53

### Which issue(s) this PR fixes 🔨

- Resolve #594

### CODE REVIEW

File: src/lib/components/messaging/stickers/StickerSelector.svelte [hunk 1]
```diff
@@ -8,10 +8,12 @@
     import { writable } from "svelte/store"
     import Spacer from "$lib/elements/Spacer.svelte"
     import { tempCDN } from "$lib/utils/CommonVariables"
+    import Fuse from "fuse.js"
 
-    const stickers = defaultManifest.stickers
-    const dispatch = createEventDispatcher()
+    // const stickers = defaultManifest.stickers
```
Comment (ashneverdawn) [inline src/lib/components/messaging/stickers/StickerSelector.svelte:13]: we can remove this commented line

**Review by ashneverdawn — APPROVED** [review]
