### PR TITLE
fix(auth): fix problem with auto login/refresh

### LINKED ISSUE #297: bug(Profile): After reloading URL user cannot change any profile data
**Issue:**
If you reload by using the root url when you get back into your account you will not be able to update your Profile Picture, Username or Status (Screenshot of errors given below)

**Screenshot/recording:**
image

https://github.com/user-attachments/assets/e73b2455-e480-44d2-b379-9184649fcb63

### LINKED ISSUE #298: bug(refresh): Account Creation flashes after reloading url
**Issue:**
When you go to the root localhost url to refresh your webpage the account creation screen flashes before logging you in 

**Screen recording:**

https://github.com/user-attachments/assets/ace87763-59ed-4fc9-8f5e-1508bae1a2ac

### LINKED ISSUE #299: bug(refresh): After refreshing URL user cannot send friend requests
**Issue:**
If user reloads webpage by going to root url, after they get into their account they will not be able to send friend requests, if they paste a did and click Add nothing happens and this error appears in console 

Screenshot 2024-07-19 at 4 07 44 PM

**STR:**
- Open account 
- Clear url at the top and reload Localhost
- Login 
- Try to paste a did and add a friend 

**Screen recording:**

https://github.com/user-attachments/assets/4f803699-5186-4dd6-a16e-3115b46ef700

### LINKED ISSUE #300: bug(refresh): After refreshing URL user cannot upload files
**Issue:**
Like the other tickets state, if you refresh the localhost and go to the root url to login, after you get into your account you cannot upload files and this error appears in console 

Screenshot 2024-07-19 at 4 11 25 PM

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Fix a problem with auto login/refreshing due to changes in #296
  - It caused warp not being initialized when refreshing
  - This change also makes it so we go directly to chat instead of unlock -> chat during auto login
  - Potentially fixes following issues? (Depends on if those were created before or after #296)
    - Fix #297
    - Fix #298 
    - Fix #299 
    - Fix #300

### CODE REVIEW

**Comment by luisecm** [comment]
The automated test showing as failed is expected for this PR, because right now asserts that user is redirected to Enter Pin screen when reloading page with enabled stay unlocked. I already added a PR in automated tests repo that will address this test once this PR is merged

File: src/lib/state/auth/index.ts [hunk 1]
```diff
@@ -72,3 +79,31 @@ class Auth {
...
+            goto(Route.Unlock)
+        } else {
+            let addressed = Object.values(get(RelayStore.state))
+                .filter(r => r.active)
+                .map(r => r.address)
+            await WarpStore.initWarpInstances(addressed)
+            log.info("Pin stored, unlocking")
+            let result = await TesseractStoreInstance.unlock(authentication.pin)
+            result.onSuccess(() => {
+                setTimeout(() => MultipassStoreInstance.initMultipassListener(), 1000)
```
Comment (InfamousVague) [inline src/lib/state/auth/index.ts:104]: Let's set this time up as a global, What is the need for this 1 second wait btw? It's okay to have it just want to understand. 

We can do something like `export const DEFAULT_WAIT_TIME = 1000`

**Review by InfamousVague — CHANGES_REQUESTED** [review]

File: src/lib/state/auth/index.ts (hunk 1 above)
Comment (Flemmli97) [reply src/lib/state/auth/index.ts:104]: thats already how its done in dev. im not too sure why as i havent written that but i would guess its the same problem we have with raygun where if its without delay it doesnt work right

**Review by InfamousVague — APPROVED** [review]
